---
- project:
    queue: kayobe
    check:
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-centos8s
        - kayobe-overcloud-tls-centos8s
        - kayobe-overcloud-host-configure-centos8s
        - kayobe-overcloud-upgrade-centos8s
        - kayobe-seed-centos8s
        - kayobe-seed-upgrade-centos8s
        - kayobe-seed-vm-centos8s

    gate:
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-centos8s
        - kayobe-overcloud-tls-centos8s
        - kayobe-overcloud-host-configure-centos8s
        - kayobe-overcloud-upgrade-centos8s
        - kayobe-seed-centos8s
        - kayobe-seed-upgrade-centos8s
        - kayobe-seed-vm-centos8s
