---
- project:
    check:
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-centos8s
        - kayobe-overcloud-ubuntu-focal
        - kayobe-overcloud-tls-centos8s
        - kayobe-overcloud-host-configure-centos8s
        - kayobe-overcloud-host-configure-ubuntu-focal
        - kayobe-overcloud-upgrade-centos8s
        - kayobe-overcloud-upgrade-ubuntu-focal
        - kayobe-seed-centos8s
        - kayobe-seed-ubuntu-focal
        - kayobe-seed-upgrade-centos8s
        - kayobe-seed-upgrade-ubuntu-focal
        - kayobe-seed-vm-centos8s
        - kayobe-seed-vm-ubuntu-focal

    gate:
      queue: kayobe
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-centos8s
        - kayobe-overcloud-ubuntu-focal
        - kayobe-overcloud-tls-centos8s
        - kayobe-overcloud-host-configure-centos8s
        - kayobe-overcloud-host-configure-ubuntu-focal
        - kayobe-overcloud-upgrade-centos8s
        - kayobe-overcloud-upgrade-ubuntu-focal
        - kayobe-seed-centos8s
        - kayobe-seed-ubuntu-focal
        - kayobe-seed-upgrade-centos8s
        - kayobe-seed-upgrade-ubuntu-focal
        - kayobe-seed-vm-centos8s
        - kayobe-seed-vm-ubuntu-focal
