---
- project:
    queue: kayobe
    check:
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-centos9s
        - kayobe-overcloud-rocky8
        - kayobe-overcloud-rocky9
        - kayobe-overcloud-ubuntu-focal
        - kayobe-overcloud-ubuntu-jammy
        - kayobe-overcloud-host-configure-centos9s
        - kayobe-overcloud-host-configure-rocky8
        - kayobe-overcloud-host-configure-rocky9
        - kayobe-overcloud-host-configure-ubuntu-focal
        - kayobe-overcloud-host-configure-ubuntu-jammy
        - kayobe-overcloud-tls-rocky9
        - kayobe-seed-rocky8
        - kayobe-seed-rocky9
        - kayobe-seed-ubuntu-focal
        - kayobe-seed-ubuntu-jammy
        - kayobe-seed-vm-rocky8
        - kayobe-seed-vm-rocky9
        - kayobe-seed-vm-ubuntu-focal
        - kayobe-seed-vm-rocky9
        - kayobe-seed-vm-ubuntu-jammy
        - kayobe-infra-vm-rocky8
        - kayobe-infra-vm-rocky9
        - kayobe-infra-vm-ubuntu-focal
        - kayobe-infra-vm-ubuntu-jammy

    gate:
      jobs:
        - openstack-tox-pep8
        - kayobe-overcloud-centos9s
        - kayobe-overcloud-rocky8
        - kayobe-overcloud-rocky9
        - kayobe-overcloud-ubuntu-focal
        - kayobe-overcloud-ubuntu-jammy
        - kayobe-overcloud-host-configure-centos9s
        - kayobe-overcloud-host-configure-rocky8
        - kayobe-overcloud-host-configure-rocky9
        - kayobe-overcloud-host-configure-ubuntu-focal
        - kayobe-overcloud-host-configure-ubuntu-jammy
        - kayobe-overcloud-tls-rocky9
        - kayobe-seed-rocky8
        - kayobe-seed-rocky9
        - kayobe-seed-ubuntu-focal
        - kayobe-seed-ubuntu-jammy
        - kayobe-seed-vm-rocky8
        - kayobe-seed-vm-rocky9
        - kayobe-seed-vm-ubuntu-focal
        - kayobe-seed-vm-rocky9
        - kayobe-seed-vm-ubuntu-jammy
        - kayobe-infra-vm-rocky8
        - kayobe-infra-vm-rocky9
        - kayobe-infra-vm-ubuntu-focal
        - kayobe-infra-vm-ubuntu-jammy
